version: '3.9'

services:
  mysql:
    container_name: mysql_construct
    # platform: linux/x86_64
    image: mysql:8.0
    ports:
      - "${MYSQL_HOST_PORT:-3306}:3306"
    environment:
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER:-root}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-mysql_db}
      - MYSQL_USER=${MYSQL_USER:-root}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-root}
    volumes:
      - ./data/mysql:/var/lib/mysql

  ###### Phpmyadmin
  phpmyadmin:
    container_name: phpmyadmin_construct
    # platform: linux/x86_64
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "${PHPMYADMIN_PORT:-8888}:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - UPLOAD_LIMIT=${MYSQL_UPLOAD_LIMIT:-200M}
    depends_on: ["mysql"]

  # backend:
  #   container_name: backend_construct
  #   # platform: linux/x86_64
  #   # image: backend
  #   build:
  #     context: .
  #     dockerfile: ./docker/backend/Dockerfile
  #   restart: unless-stopped
  #   ports:
  #     - "${PORT_API:-2209}:2209"
  #   environment:
  #     - NODE_ENV=production
  #     - JWT_ACCESS_TOKEN_SECRET=${JWT_ACCESS_TOKEN_SECRET:-construct_access}
  #     - JWT_ACCESS_EXPIRES=${JWT_ACCESS_EXPIRES:-1d}
  #     - JWT_REFRESH_TOKEN_SECRET=${JWT_REFRESH_TOKEN_SECRET:-construct_refresh}
  #     - JWT_REFRESH_EXPIRES=${JWT_REFRESH_EXPIRES:-3d}
  #     - IS_MULTI_USER=${IS_MULTI_USER:-0}
  #   depends_on:
  #     - mysql
  #     - phpmyadmin
 
  # ##### Nginx
  # nginx:
  #   container_name: nginx_construct
  #   image: nginx:latest
  #   volumes:
  #     - "./backend:/var/www/api"
  #     - "./docker/nginx/.htpasswd:/etc/nginx/.htpasswd"
  #     - "./docker/nginx/conf.d/${BUILD_ENV:-local}.conf:/etc/nginx/nginx.conf"
  #   ports: ["${NGINX_HOST_PORT:-80}:80"]
  #   environment:
  #     SERVER_NAMES_HASH_BUCKET_SIZE: 64
  #   depends_on:
  #     - backend